# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Minecraft
minecraft_version=1.20.1
minecraft_version_range=[1.20,1.20.2)

# Forge
forge_id=forge
forge_version=47.4.16
forge_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1

# Mod
mod_group_id=xiao.armorscaling
mod_id=armorscaling
mod_name=TaCZ Armor Scaling
mod_license=GPL-3.0 license
mod_version=0.0.0
mod_credits=XiaoColorful, XColorful
mod_authors=XiaoColorful
mod_description=

mod_issue_url=https://github.com/XColorful/TaCZ-Armor-Scaling/issues
mod_display_url=https://github.com/XColorful/TaCZ-Armor-Scaling/wiki
mod_logo_file=logo.png

pack_description=TaCZ Armor Scaling resources
pack_format=15

# Dependencies
tacz_version_range=[1.0.2,]
battleroyale_version_range=[0.5.1,)

# CompileOnly
# tacz-1.20.1-1.1.7-hotfix.jar
tacz_curse_maven=curse.maven:timeless-and-classics-zero-1028108:7401617
# battleroyale-0.5.1-dev1-forge1.20.1.jar
battleroyale_curse_maven=curse.maven:custom-battleroyale-1277855:7700606