plugins {
    id 'java-library'
    id 'net.neoforged.gradle.userdev' version '7.1.39'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"

    compileOnly "${cgc_curse_maven}"
    compileOnly "${battleroyale_curse_maven}"
}

jar {
    archiveBaseName.set(mod_id)
    archiveVersion.set(mod_version)
    archiveClassifier.set("core")
}